### ISSUE TITLE
Connection Refused in Ionic on Android

### ISSUE THREAD

**Issue by jstevej** [blocshop/sockets-for-cordova#10]
When using sockets-for-cordova in an ionic application, I get the error at the end of this message when calling Socket.open().

I am using the exact same code in a non-ionic cordova app, and it works fine.

I have verified that `<uses-permission android:name="android.permission.INTERNET" />` is making it into my AndroidManifest.xml, and I have added the following to my config.xml in case it is a cordova whitelist issue.

    <access origin="*"/>
    <allow-navigation href="*"/>
    <allow-intent href="*"/>

I also see the following message regarding whitelist, but I have not been able to resolve it, and I don't know if it is relevant or not.

D/SystemWebChromeClient(20861): file:///android_asset/www/plugins/cordova-plugin-whitelist/whitelist.js: Line 25 : No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.
I/chromium(20861): [INFO:CONSOLE(25)] "No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.", source: file:///android_asset/www/plugins/cordova-plugin-whitelist/whitelist.js (25)

Here is the error I get when trying Socket.open():

D/SystemWebChromeClient(28872): file:///android_asset/www/js/connect.js: Line 11 : Connect.connect() 192.168.2.193
I/chromium(28872): [INFO:CONSOLE(11)] "Connect.connect() 192.168.2.193", source: file:///android_asset/www/js/connect.js (11)
E/SocketAdapterImpl(28872): Error during connecting of socket
E/SocketAdapterImpl(28872): android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
E/SocketAdapterImpl(28872): 	at libcore.io.Posix.connect(Native Method)
E/SocketAdapterImpl(28872): 	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
E/SocketAdapterImpl(28872): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
E/SocketAdapterImpl(28872): 	at libcore.io.IoBridge.connect(IoBridge.java:122)
E/SocketAdapterImpl(28872): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
E/SocketAdapterImpl(28872): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
E/SocketAdapterImpl(28872): 	at java.net.Socket.connect(Socket.java:882)
E/SocketAdapterImpl(28872): 	at java.net.Socket.connect(Socket.java:825)
E/SocketAdapterImpl(28872): 	at cz.blocshop.socketsforcordova.SocketAdapterImpl$1.run(SocketAdapterImpl.java:38)
E/SocketAdapterImpl(28872): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/SocketAdapterImpl(28872): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/SocketAdapterImpl(28872): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/SocketAdapterImpl(28872): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/SocketAdapterImpl(28872): 	at java.lang.Thread.run(Thread.java:818)
D/SystemWebChromeClient(28872): file:///android_asset/www/js/control.js: Line 10 : Control
I/chromium(28872): [INFO:CONSOLE(10)] "Control", source: file:///android_asset/www/js/control.js (10)
W/BindingManager(28872): Cannot call determinedVisibility() - never saw a connection for the pid: 28872

**Comment by jstevej** [comment]
I added the following meta tag to my index.html and made the Content-Security-Policy warning go away, but I'm still having the same ECONNREFUSED problem.

    <meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src: 'self' 'unsafe-inline' 'unsafe-eval'">

**Comment by jstevej** [comment]
The only significant differences I can find between the non-ionic project that works and the ionic/angular project that doesn't are the following:

ionic: android platform version 4.0.0, cordova-plugin-whitelist installed
non-ionic: android platform version 3.7.1, cordova-plugin-whitelist NOT installed

I'm using cordova 5.0.0.

**Comment by jstevej** [comment]
I finally found it. Embarrassingly dumb mistake on my part, not an issue with sockets-for-cordova.

**Comment by sameer777** [comment]
@jstevej : Hii please help me in thi issue I got also same issue file download file from server to android mobile. How you can solve this issue?? Please help me . Thanks.

**Comment by ycktw** [comment]
I got something similar to this issue. It seems not a critical issue, but clues are important for us to find out the root cause. Would someone please provide comments or idea for me ?
