### ISSUE TITLE
Socket is not defined

### ISSUE THREAD

**Issue by dsbcourtney** [blocshop/sockets-for-cordova#13]
I am having real trouble getting this plugin to work. I am using windows and phonegap 5.1.1. Should I be able to run the index.html locally when it is built in the platforms/ios folder? 

I am getting Socket is not defined when I put in the line of code

"var socket = new Socket();"

cordova.js and js/index.js are referenced above it and I can see the reference to the socket.js file in the console..

Thanks in advance.

**Comment by andrepsc3011** [comment]
I have the same problem!

**Comment by mobratil** [comment]
Hi,
maybe I didn't understand your problem. This plugin can be run only on mobil device (ios, android, wp). Be sure, that you run your code after 'deviceready' event is fired.

**Comment by dsbcourtney** [comment]
Thanks, yes I do that but debugging is pretty much non existent so i cannot see what the problem is that is stopping it from working. The console within phonegap doesn't send me any error messages and when i try using xcode and the debugger there again no errors are thrown. The on success and on failure functions just don't get executed which makes me believe it the files are not getting referenced at all.

**Comment by andrepsc3011** [comment]
I'm using the Intel XDK to develop an app for android and iOS. When I saved the code displays the error "Socket is not defined," but when I build (in the cloud) the app it works in parts. I can connect to my server and receive data but still can not send anything. I'm using a code similar to the example.
My code:

function sendData() {

```
    var input = "313000000ios";
    var data = new Uint8Array(input.length);
    for (var i = 0; i < data.length; i++) {
      data[i] = input.charCodeAt(i);
    }
    socket.write(
            data,
            function(){
                alert('Data successful sended!');
            },
            function(message){
                alert('Data send error: '+message);
            }
    );
```

}

If I use "window.socket.write()" I can send, but just receive data when disconnect to the server.
What is wrong?

Thanks!

**Comment by mobratil** [comment]
@andrepsc3011 your code snippet seems ok, but error message "Socket is not defined" means that plugin was not loaded correctly. Are you sure, that your setup of cordova project is ok?
Checkout this small sample project: https://github.com/blocshop/sockets-for-cordova-tester
It contains basic usage of socket plugin.

@dsbcourtney Can you try to debug native code in xcode?

**Comment by 0x6e69636f** [comment]
Actually, I still have this issue, even in a brand new app with just this : 

```
    initialize: function() {
        this.bindEvents();
        var socket = new Socket();
    },
```

I installed the plugin from Github as it's not available anymore on npm

**Comment by 0x6e69636f** [comment]
Ok my bad _you have to call it AFTER `deviceReady` event has been fired_
