### ISSUE TITLE
receive method - Cordova sample for receving tcp message

### ISSUE THREAD

**Issue by Mikis93** [blocshop/sockets-for-cordova#19]
Hi,

I'm facing an issue related to socket's Receive function when we call it in an app that was built using PhoneGapBuild.

Within the library there is the receive method?
there is a way to implement it?
I have to receive data from a socket connected to a specific address.

Looking forward to answers and support. Thanks.

**Comment by azazlhr** [comment]
Hi,

There is no receive method in this library, however, you can receive data from a socket using onData Event Handler after you have established a connection to socket/host.

Details regarding all functions and Event Handlers exposed by this library is given here:
https://github.com/blocshop/sockets-for-cordova

Sample Code:

``` javascript
var socket = new Socket();
// invoked after new batch of data is received (typed array of bytes Uint8Array)
socket.onData = function (dataPacket) {
                try {                                       
                    dpParser.ParseDataPakcet(dataPacket);
                }
                catch (ex) {
                    RaiseExceptionEvent(ex);
                }
            };
```

Hope this would help.
