### ISSUE TITLE
plugin end up with: undefined is not a function in cordova.js

### ISSUE THREAD

**Issue by telcy** [blocshop/sockets-for-cordova#6]
I am not sure if you can help me with this. But I have no clue what this problem produces. http://stackoverflow.com/questions/27882086/phonegap-cordova-socket-plugins-end-up-with-undefined-is-not-a-function-in-co

**Comment by mobratil** [comment]
Seems like prolem with initialization of cordova. Did you wait until `deviceready` is called, before you run your script?

**Comment by telcy** [comment]
Seems that phonegap does not load the js include in the right order. I have put the include of cordova.js in the head section of my index.html and it does work now. Really strange

How do I use this plugin and listen to a port? Sending data works great. But I have no idea how the listen could work.

**Comment by mobratil** [comment]
You can listen to incoming data using `onData` event listener. Here is example:
```
socket.onData = function(data) {
  // this method is invoked after new batch of data is received
};
```

Variable `data` is byte array - instance of Uint8Array (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array)

You can convert this data to string or to anything you want.

For more details, look at this repository:
https://github.com/blocshop/sockets-for-cordova-tester/blob/master/www/index.html

it is simple working cordova app, that uses this socket API.

**Comment by telcy** [comment]
Thank you for this fast response mobratil. I really appreciate your work. The onData Event does not get fired. I am doing the same in C# with: this.tcpListener = new TcpListener(IPAddress.Any, 51213); So I am listening to AnyIP on Port 51213. Maybe it has sth to do with the emulation.

**Comment by mobratil** [comment]
I had problems with any Cordova plugin on Android emulator. I just tried it now and I wasn't even able to instantiate Socket object. It is probably because Cordova was not loaded within some period of time.
There is message in console saying:
```
deviceready has not fired after 5 seconds.
```

Please, try it on real device.

**Comment by elielmathe** [comment]
I got the same issues. I think that it would be okay to add a listen method to the object Socket of your plugin. True, we are getting data by onData() but we are not listenning from any port as it could be in Java
ServerSocket serverSocket = new ServerSocket(4000);
Socket socket = serverSocket.accept();

I don't know how to write a plugin but I could suggest you to add listen(port).

**Comment by BeyondIntelligence** [comment]
Did anyone resolve this issue ?
