### ISSUE TITLE
How ot use this plugin?

### ISSUE THREAD

**Issue by multilexus** [blocshop/sockets-for-cordova#7]
Hi, I'm new to cordova and trying to use it with Ionic Framework. I have an existing project that works and has multiple pages. 

I've added this plugin using: "cordova plugin add cz.blocshop.socketsforcordova" and I confirmed that it was added successfully under plugins folder.

After that I added the following code in my controller, which is called with a press of a "Connect" button on the page: "var socket = new Socket();"

When I run the code in Chrome browser with Netbeans connector, I get the following error: 

Error: Can't find variable: Socket
connect@http://localhost:8383/nj_obd/js/controller/inspectionController.js:45:23
http://localhost:8383/nj_obd/lib/ionic/js/ionic.bundle.js:19687:25
http://localhost:8383/nj_obd/lib/ionic/js/ionic.bundle.js:42909:20
$eval@http://localhost:8383/nj_obd/lib/ionic/js/ionic.bundle.js:21549:27
$apply@http://localhost:8383/nj_obd/lib/ionic/js/ionic.bundle.js:21647:27
http://localhost:8383/nj_obd/lib/ionic/js/ionic.bundle.js:42908:18
http://localhost:8383/nj_obd/lib/ionic/js/ionic.bundle.js:11841:13
forEach@[native code]
forEach@http://localhost:8383/nj_obd/lib/ionic/js/ionic.bundle.js:9351:17
eventHandler@http://localhost:8383/nj_obd/lib/ionic/js/ionic.bundle.js:11840:11
dispatchEvent@[native code]
triggerMouseEvent@http://localhost:8383/nj_obd/lib/ionic/js/ionic.bundle.js:2740:19
tapClick@http://localhost:8383/nj_obd/lib/ionic/js/ionic.bundle.js:2729:19
tapMouseUp@http://localhost:8383/nj_obd/lib/ionic/js/ionic.bundle.js:2799:12 (12:04:48:580 | error)

Any idea what that means? Thanks!

**Comment by mobratil** [comment]
Hi, thanks for your post.
As I understand, you are trying to run this plugin in Chrome browser. This plugin supports only these platforms: Android, iOS or WP8. Currently it doesn't support browser platform.

To run this plugin in web browser, you have to write some proxy in pure javascript (probably through websockets), that implements Socket interface.
