### ISSUE TITLE
LICENCE missing

### ISSUE THREAD

**Issue by gianarb** [blocshop/sockets-for-cordova#8]
Hi! What is the Licence for this project? 
Thansk!

**Comment by mobratil** [comment]
Hi, licence of this project is BSD. I'm going to add it to source code soon.

Thanks.

Martin

**Comment by gianarb** [comment]
Thanks!

2015-04-23 13:59 GMT+02:00 Martin Obrátil <notifications@github.com>:

> Hi, licence of this project is BSD. I'm going to add it to source code
> soon.
>
> Thanks.
>
> Martin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blocshop/sockets-for-cordova/issues/8#issuecomment-95559845>
> .
>



-- 
Gianluca Arbezzano
www.gianarb.it

**Comment by mmuszkow** [comment]
Hi,
I'd like to use your lib, but the lack of license is blocking me. Can you add it to repo?

Thanks,
MM

**Comment by gianarb** [comment]
:+1:

**Comment by mobratil** [comment]
I added BSD license into Readme. Is it sufficient?

**Comment by mmuszkow** [comment]
Yes, thank you very much :)
